name: Deploy to EC2 and S3

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to API EC2
        env:
          KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.API_HOST }}
          USER: ubuntu
        run: |
          ssh -i "$KEY" $USER@$HOST << 'EOF'
          set -e
          cd /home/ubuntu/D03_AWS_FULLSTACK_NOV24
          git pull origin main
          docker compose down
          docker compose up -d api
          EOF

  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Frontend
        run: |
          cd GreenSphere-web
          npm install
          npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 sync dist/ s3://teste-excluir123 --profile Miyata
